name: CD

on:
  push:
    branches:
      - main

concurrency: deployments

env:
  IMAGE_NAME: gcr.io/tobysmith-uk/tobysmith-uk
  ENVIRONMENT_NAME: Production

jobs:
  ci:
    name: Run CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
      - name: Login to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Deploy Docker image
        run: >
          gcloud run deploy ${{ secrets.GCP_APP_NAME }}
          --image ${{ env.IMAGE_NAME }}
          --region europe-west1
          --platform managed
